// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFJmPlwc5RiU7lbnB_fYIXdThBO0jFH68',
    appId: '1:171701293716:web:ce8e3a24807967b0731a81',
    messagingSenderId: '171701293716',
    projectId: 'easespotter',
    authDomain: 'easespotter.firebaseapp.com',
    storageBucket: 'easespotter.firebasestorage.app',
    measurementId: 'G-YTYXETTNJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1lXnFfGfr2ff6iDvwIYNlpukA-Ubn168',
    appId: '1:171701293716:android:e28725cc2e2bd44b731a81',
    messagingSenderId: '171701293716',
    projectId: 'easespotter',
    storageBucket: 'easespotter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfFmKTRcCVI8rs9_sKw_XCnYkNBVzGiA8',
    appId: '1:171701293716:ios:8aa288357ca8dd4b731a81',
    messagingSenderId: '171701293716',
    projectId: 'easespotter',
    storageBucket: 'easespotter.firebasestorage.app',
    iosBundleId: 'com.samuel.easespotter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfFmKTRcCVI8rs9_sKw_XCnYkNBVzGiA8',
    appId: '1:171701293716:ios:8aa288357ca8dd4b731a81',
    messagingSenderId: '171701293716',
    projectId: 'easespotter',
    storageBucket: 'easespotter.firebasestorage.app',
    iosBundleId: 'com.samuel.easespotter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFJmPlwc5RiU7lbnB_fYIXdThBO0jFH68',
    appId: '1:171701293716:web:7bcbbfc37b0ad54a731a81',
    messagingSenderId: '171701293716',
    projectId: 'easespotter',
    authDomain: 'easespotter.firebaseapp.com',
    storageBucket: 'easespotter.firebasestorage.app',
    measurementId: 'G-7BEYRDQ256',
  );
}
